name: Publish hintekk_core to PyPI dev

on:
  push:
    branches:
      - master
      - release
    paths:
      - 'xayn-core/**'
      - '.github/workflows/publish_xayn_core.yml'
  pull_request:
    branches:
      - master
    paths:
      - 'xayn-core/**'
      - '.github/workflows/publish_xayn_core.yml'

jobs:
  publish:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'
      
      - name: Linter
        run: |
          python -m pip install --upgrade pip
          pip install pycodestyle
          pycodestyle --ignore=E501 xayn-core/*.py
          pycodestyle --ignore=E501 xayn-core/xayn_core/*.py
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ github.ref_name == 'master' && secrets.AWS_ACCESS_KEY_ID || github.ref_name == 'release' && secrets.AWS_ACCESS_KEY_ID_PROD || '' }}
          aws-secret-access-key: ${{ github.ref_name == 'master' && secrets.AWS_SECRET_ACCESS_KEY || github.ref_name == 'release' && secrets.AWS_SECRET_ACCESS_KEY_PROD || '' }}
          aws-region: us-east-1
      
      - name: Calculate pypi bucket name
        id: pypi_bucket
        run: |
          if [ "${GITHUB_REF_NAME}" = "master" ]; then
            echo "pypi_bucket=xayn-core-dev" >> $GITHUB_OUTPUT
          elif [ "${GITHUB_REF_NAME}" = "release" ]; then
            echo "pypi_bucket=xayn-core-prod" >> $GITHUB_OUTPUT
          else
            echo "pypi_bucket=" >> $GITHUB_OUTPUT
          fi

      - name: Build and Publish to PyPI
        run: |
          python -m pip install --upgrade pip
          pip install setuptools s3pypi MarkupSafe build
          cd xayn-core
          python setup.py sdist bdist_wheel
          s3pypi upload -b ${{ steps.pypi_bucket.outputs.pypi_bucket }} -f dist/*

          
      
